"""Central configuration for the modular book-spine pipeline."""

SUPPORTED_IMAGE_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".webp",
    ".bmp",
    ".tif",
    ".tiff",
    ".heic",
    ".heif",
    ".avif",
}

YOLO_CONFIDENCE_THRESHOLD = 0.50
YOLO_IOU_THRESHOLD = 0.40

OCR_RESULT_SCORE_THRESHOLD = 0.80

LOCAL_MATCH_SCORE_CUTOFF = 80
GOOGLE_BOOKS_MATCH_SCORE_CUTOFF = 60
CATALOG_DUPLICATE_SCORE_CUTOFF = 90

RECOMMENDATION_TOP_K = 5
RECOMMENDATION_QUERY_SCORE_CUTOFF = 0.35

GOOGLE_BOOKS_TIMEOUT_SECONDS = 5
GOOGLE_BOOKS_MAX_RETRIES = 3
GOOGLE_BOOKS_MAX_RESULTS = 5

MIN_DESCRIPTION_WORDS = 0

PREPROCESS_TARGET_HEIGHT = 300
PREPROCESS_TARGET_WIDTH = 750

CLAHE_CLIP_LIMIT = 2.0
CLAHE_TILE_GRID_SIZE = (8, 8)
SHARPEN_SIGMA_X = 1.0
SHARPEN_WEIGHT = 1.35
SHARPEN_BLUR_WEIGHT = -0.35

DET_UNCLIP_RATIO = 1.2